import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary:    { DEFAULT: "hsl(var(--primary))",    foreground: "hsl(var(--primary-foreground))" },
        secondary:  { DEFAULT: "hsl(var(--secondary))",  foreground: "hsl(var(--secondary-foreground))" },
        destructive:{ DEFAULT: "hsl(var(--destructive))",foreground: "hsl(var(--destructive-foreground))" },
        muted:      { DEFAULT: "hsl(var(--muted))",      foreground: "hsl(var(--muted-foreground))" },
        accent:     { DEFAULT: "hsl(var(--accent))",     foreground: "hsl(var(--accent-foreground))" },
        popover:    { DEFAULT: "hsl(var(--popover))",    foreground: "hsl(var(--popover-foreground))" },
        card:       { DEFAULT: "hsl(var(--card))",       foreground: "hsl(var(--card-foreground))" },
        moonlight:  "hsl(var(--moonlight))",
        rose:       "hsl(var(--rose))",
        "rose-deep":"hsl(var(--rose-deep))",
        lilac:      "hsl(var(--lilac))",
        midnight:   "hsl(var(--midnight))",
        starlight:  "hsl(var(--starlight))",
        parchment:  "hsl(var(--parchment))",
        "parchment-deep": "hsl(var(--parchment-deep))",
        ink:        "hsl(var(--ink))",
        candle:     "hsl(var(--candle))",
        sepia:      "hsl(var(--sepia))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      backgroundImage: {
        'gradient-romance': 'var(--gradient-romance)',
        'gradient-midnight': 'var(--gradient-midnight)',
        'gradient-parchment': 'var(--gradient-parchment)',
        'gradient-final': 'var(--gradient-final)',
      },
      boxShadow: {
        'glow-rose':  'var(--glow-rose)',
        'glow-moon':  'var(--glow-moon)',
        'glow-candle':'var(--glow-candle)',
        'deep':       'var(--shadow-deep)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":        { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in-slow":   { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "scale-in":       { "0%": { opacity: "0", transform: "scale(0.92)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "letter-in":      { "0%": { opacity: "0", transform: "translateY(40px) scale(0.9)", filter: "blur(8px)" }, "100%": { opacity: "1", transform: "translateY(0) scale(1)", filter: "blur(0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "fade-in":        "fade-in 0.9s ease-out both",
        "fade-in-slow":   "fade-in-slow 2.4s ease-out both",
        "scale-in":       "scale-in 0.8s ease-out both",
        "letter-in":      "letter-in 1.2s cubic-bezier(.2,.7,.2,1) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
